### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [Lanchon/sigspoof-checker#1]
Seems like a no-brainer, no?

**Comment by Lanchon** [comment]
but i don't know how to do this.

**Comment by ale5000-git** [comment]
You should look at [Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy), [Inclusion How-To](https://f-droid.org/wiki/page/Inclusion_How-To) and [FAQ - App Developers](https://f-droid.org/wiki/page/FAQ_-_App_Developers).

**Comment by Lanchon** [comment]
thanks!

https://gitlab.com/fdroid/rfp/issues/125

**Comment by ale5000-git** [comment]
@Lanchon: They have replied but they are waiting your reply for reproducible builds.

> F-Droid supports reproducible builds of apps, so that anyone can run the build process again and reproduce the same APK as the original release. This means that F-Droid can verify that an app is 100% free software while still using the original developer’s APK signatures.

More info [here](https://eighthave.gitlab.io/fdroid-website/docs/Reproducible_Builds/).

**Comment by ale5000-git** [comment]
@Lanchon: It may be a good idea to also update gradle wrapper to 3.5 and com.android.tools.build:gradle to 2.3.2

**Comment by Lanchon** [comment]
sorry i'm way too busy. why do they want repro builds? no need at all.

**Comment by ale5000-git** [comment]
@Lanchon: It is preferable (not obligatory).

Without reproducible builds F-Droid builds are signed with F-Droid signature, instead with reproducible builds F-Droid builds are signed with your signature.

So without reproducible builds if a person install this app from GitHub then it cannot update from F-Droid for the different signature and it is annoying.
And if an user installed the app from F-Droid then it cannot update it from GitHub (where it is released earlier) and everyone that want to update it have to wait.

**Comment by Lanchon** [comment]
yes, i know! i don't care at all, lol

this app doesn't even have state, you can remove it and then install it again :)

plus, this is a test app: you use it once or twice, then remove it.

if needed i'd rather just update the build here with F-Droid's

**Comment by ale5000-git** [comment]
@picsi: It is now on F-Droid => https://f-droid.org/repository/browse/?fdid=lanchon.sigspoof.checker

**Comment by nicolasmaia** [comment]
Woo, thanks @ale5000-git and @Lanchon :)
