### ISSUE TITLE
Wrong detection

### ISSUE THREAD

**Issue by walrus543** [Lanchon/sigspoof-checker#2]
Hi,

I'm running Android 7.1.2 (custom ROM based on Lineage OS which has the built-in signature spoofing patch).
All features are checked in microG settings app > self-check.

![](https://framapic.org/WzMHZLFoZInr/326TWhKkdC39)

**Comment by Lanchon** [comment]
detection works, AFAIK. i even publish a rom patcher to implement sigspoof (see lanchon haystack).

your rom could have sigspoof capability only for microG (tied to microG's public certificate). this has been proposed in projects such as CyanogenMod, and it is insulting and contrary to free software principles in that you are forbidden to build, hack, or contribute to (you cannot test your contributions) the microG Project.

alternatively, some other mechanism might be denying sigspoof to this app. have you check app permissions for this app in the OS settings? some Android builds require that you grant sigspoof permission explicitly to apps.

**Comment by ale5000-git** [comment]
@Primokorn: Maybe you have to enable signature spoofing permission for this app (separate from the one for microG).

**Comment by walrus543** [comment]
You are right. I didn't grant the permission.
The check passes now.

**Comment by ale5000-git** [comment]
@Lanchon: Maybe should be added to the readme this information about granting the app specific permission on some ROM.

**Comment by Lanchon** [comment]
thank you both!

this is sort of a bug. the app should request the permission, not just use it.
this is why @Primokorn got into trouble in the first place.

**Comment by Lanchon** [comment]
see #3.
