### ISSUE TITLE
FakeGApps

### ISSUE THREAD

**Issue by thermatk** [Lanchon/sigspoof-checker#4]
Hi!
Please detect the case of installed FakeGApps, maybe by package. People test with your app and say there is no spoofing, because FakeGApps only spoofs for Play Store and Play Services, which must be enough.
Thanks!

**Comment by ale5000-git** [comment]
In my opinion it doesn't make sense, this app is to test spoofing without microG.
For spoofing specific to microG you could just see the internal microG self check.

**Comment by thermatk** [comment]
@ale5000-git that's totally conflicting with the apps description, or the description is not clear enough

> This app tests the signature spoofing capability of your Android OS as required by the microG Project

And what are other uses for spoofing?

**Comment by ale5000-git** [comment]
This is to be used before installing microG to know if the ROM support signature spoofing.
If you already have microG you can see it from the microG self check.

FakeGApps fake signature spoofing only for microG so only microG can know if it is working.

**Comment by Lanchon** [comment]
this will absolutely not be done. i support an open signature spoofing mechanism and oppose limiting the mechanism to one app or app signature. lineage.microg.org also appears to do just that, and IMHO it is a very bad decision. if you have a "closed" sigspoof mechanism, you are on your own; i won't support it.
